// Copyright 2026 Boundary Authors
// SPDX-License-Identifier: Apache-2.0

const fs = require('fs');
const path = require('path');

/**
 * Next.js config plugin wrapper.
 * Enables experimental.instrumentationHook and wires up Boundary SDK.
 */
function withBoundary(nextConfig = {}) {
  const userExperimental = nextConfig.experimental || {};

  return {
    ...nextConfig,
    experimental: {
      ...userExperimental,
      instrumentationHook: true,
    },
    webpack: (config, options) => {
      // Allow custom webpack config from user to run first
      if (typeof nextConfig.webpack === 'function') {
        config = nextConfig.webpack(config, options);
      }
      return config;
    },
  };
}

/**
 * Automatically inspect a Next.js repository root and safely wire up
 * `instrumentation.ts` and `next.config.*`.
 */
function injectNextConfig(projectDir) {
  const root = path.resolve(projectDir || '.');
  const results = {
    detected: false,
    instrumentationCreated: false,
    configUpdated: false,
    configPath: null,
    notes: [],
  };

  const pkgJsonPath = path.join(root, 'package.json');
  if (!fs.existsSync(pkgJsonPath)) {
    return results;
  }

  try {
    const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8'));
    const allDeps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
    if (!allDeps['next']) {
      return results;
    }
    results.detected = true;
  } catch (err) {
    results.notes.push(`Failed to parse package.json: ${err.message}`);
    return results;
  }

  // 1. Check or generate instrumentation.ts / instrumentation.js
  const possibleInstrumentationPaths = [
    path.join(root, 'instrumentation.ts'),
    path.join(root, 'instrumentation.js'),
    path.join(root, 'src', 'instrumentation.ts'),
    path.join(root, 'src', 'instrumentation.js'),
  ];

  const existingInst = possibleInstrumentationPaths.find(p => fs.existsSync(p));
  if (!existingInst) {
    const targetFile = fs.existsSync(path.join(root, 'src'))
      ? path.join(root, 'src', 'instrumentation.ts')
      : path.join(root, 'instrumentation.ts');

    const templateContent = `// Auto-generated by Boundary
export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    const { register } = await import('@boundary/nextjs/instrumentation');
    await register();
  }
}
`;
    fs.writeFileSync(targetFile, templateContent, 'utf8');
    results.instrumentationCreated = true;
    results.notes.push(`Created ${path.relative(root, targetFile)}`);
  } else {
    results.notes.push(`Existing instrumentation found at ${path.relative(root, existingInst)}`);
  }

  const possibleConfigs = [
    'next.config.mjs',
    'next.config.js',
    'next.config.ts',
  ];

  const foundConfig = possibleConfigs.find(c => fs.existsSync(path.join(root, c)));
  if (foundConfig) {
    const fullPath = path.join(root, foundConfig);
    results.configPath = fullPath;
    let content = fs.readFileSync(fullPath, 'utf8');

    if (!content.includes('instrumentationHook') && !content.includes('withBoundary')) {
      if (foundConfig.endsWith('.mjs')) {
        if (content.includes('const nextConfig = {')) {
          content = content.replace(
            'const nextConfig = {',
            'const nextConfig = {\n  experimental: { instrumentationHook: true },'
          );
          fs.writeFileSync(fullPath, content, 'utf8');
          results.configUpdated = true;
        }
      } else if (foundConfig.endsWith('.js')) {
        if (content.includes('module.exports = {')) {
          content = content.replace(
            'module.exports = {',
            'module.exports = {\n  experimental: { instrumentationHook: true },'
          );
          fs.writeFileSync(fullPath, content, 'utf8');
          results.configUpdated = true;
        }
      }
      results.notes.push(`Configured experimental.instrumentationHook in ${foundConfig}`);
    } else {
      results.notes.push(`instrumentationHook already configured in ${foundConfig}`);
    }
  }

  return results;
}

module.exports = {
  withBoundary,
  injectNextConfig,
};
